config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  resources :groups do
    resources :entities
  end

  # filter :locale

  root "public#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.is? :admin
      can :manage, :all
    else
      can :manage, Group, author_id: user.id
      can :manage, Entity, author_id: user.id
      can :manage, User, id: user.id
    end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
  has_many :groups, foreign_key: 'entitiy_id'

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
  has_many :entities, foreign_key: 'group_id'

  has_one_attached :icon

  validates :name, presence: true
  validates :icon, presence: false
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  has_many :groups, foreign_key: 'author_id'
  has_many :entities, foreign_key: 'author_id'
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable,:confirmable,:recoverable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2, :github],
         authentication_keys: [:login], confirmation_keys: [:login]

  # validates :name, presence: true

  def is?(role)
    self.role == role.to_s
  end

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do | user |
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = provider_data.info.name   # assuming the user model has a name
      user.skip_confirmation!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :update_allowed_params, if: :devise_controller?
  

  protected

  def update_allowed_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[name email password password_confirmation current_password])
    devise_parameter_sanitizer.permit(:sign_in, keys: %i[email password])
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  def new
    @entity = Entity.new
  end

  def create
    @entity = Entity.new(entity_params)
    @entity.group_id = params[:group_id]
    @entity.author_id = current_user.id
    @entity.save

    if @entity.save
      redirect_to group_path(@entity.group_id), success: 'Transaction was successfully created.'
    else
      render 'new', error: 'Transaction was not created.'
    end
  end

  # def edit
  #   @entity = Entity.find(params[:id])
  # end

  # def update
  #   @entity = Entity.find(params[:id])
  #   @entity.update(entity_params)
  #   redirect_to group_path(@entity.group_id)
  # end

  # def destroy
  #   @entity = Entity.find(params[:id])
  #   @entity.destroy
  #   redirect_to group_path(@entity.group_id)
  # end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount, :group_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])
    @entities = @group.entities
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  # def edit
  # end

  # POST /groups
  # POST /groups.json
  def create
    @name = group_params[:name]
    @author = current_user
    @group = Group.new(name: @name, author_id: @author.id)
    @group.icon.attach(params[:group][:icon])

    if @group.save
      redirect_to @group, success: 'Category was successfully created.'
    else
      render :new, error: 'Category was not created.'
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  # def update
  #   respond_to do |format|
  #     if @group.update(group_params)
  #       format.html { redirect_to @group, notice: 'Group was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @group }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @group.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /groups/1
  # DELETE /groups/1.json
  # def destroy
  #   @group.destroy
  #   respond_to do |format|
  #     format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private

  def group_params
    params.require(:group).permit(:name, :user_id, :icon)
  end
end

app/controllers/omniauth_controller.rb
class OmniauthController < ApplicationController
  # skip_before_action :verify_authenticity_token, only: :facebook

  def facebook
    @user = User.create_from_provider_data(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      flash[:notice] = "You are signed in successfully."
      # set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    @user = User.create_from_provider_data(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      flash[:notice] = "You are signed in successfully."
      # set_flash_message(:notice, :success, kind: "Google") if is_navigational_format?
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def github
    @user = User.create_from_provider_data(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      flash[:notice] = "You are signed in successfully."
      # set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    flash[:error] = "There was a problem signing you in. Please register or try signing in later."
    redirect_to new_user_registration_url
  end
  
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_helper.rb
module OmniauthHelper
end

app/views/entities/_form.html.erb
<%= form_for @entity ,url:group_entities_path(params[:group_id]) do |f| %>
<div class="space-y-2 mx-9 flex flex-col bg-[#fff] px-11 py-6 rounded-lg">
  <div class="mt-8 content-center flex flex-col space-y-2">
    <%= f.label :name ,class:"text-primary"%>
    <%= f.text_field :name,class:"text-primary w-[75%]" %>
  </div>

  <div class="mt-8 content-center flex flex-col space-y-2">
    <%= f.label :amount,class:"text-primary"%>
    <%= f.number_field :amount,class:"text-primary p-2 w-[50%]"%>
  </div>

     <%= f.submit "Add transaction", class: " w-fit flex bg-secondary text-[#fff] p-2 tracking-wide uppercase
                                font-semibold  focus:outline-none focus:shadow-outline hover:bg-indigo-600 shadow-lg cursor-pointer transition ease-in duration-300"%>

</div>
<% end %>

app/views/entities/new.html.erb
<div>
  <h1 class=" text-center p-3 text-xl font-bold text-text-primary">Add New Transaction</h1>

    <%= render 'form' %>
<div>

app/views/groups/_form.html.erb
<%= form_for @group ,url:groups_path do |f| %>
<div class="space-y-2 mx-9 flex flex-col bg-[#fff] px-11 py-6 rounded-lg">
  <div class="mt-8 content-center flex flex-col space-y-2">
    <%= f.label :name ,class:"text-primary"%>
    <%= f.text_field :name,class:"text-primary w-[75%]" %>
  </div>

  <div class="mt-8 content-center flex flex-col space-y-2">
    <%= f.label :icon,class:"text-primary"%>
    <%= f.file_field :icon,class:"text-primary"%>
  </div>

     <%= f.submit "Create Category", class: " w-fit flex bg-secondary text-[#fff] p-2 tracking-wide uppercase
                                font-semibold  focus:outline-none focus:shadow-outline hover:bg-indigo-600 shadow-lg cursor-pointer transition ease-in duration-300"%>

</div>
<% end %>

app/views/groups/index.html.erb
<div class="relative flex flex-col gap-2 mt-3 overflow-y-scroll">
 <%= link_to 'New Category', new_group_path,class: " hidden sm:block md:mt-3 self-center md:bottom-6 w-25 text-center bg-secondary hover:bg-primary hover:opacity-50 text-[#fff] font-bold py-3 px-4 border border-primary rounded" %>
  <% @groups.each do |group| %>
  <%if can? :manage,group%>
    <%= link_to group_path(id:group.id),method: 'get' do%>
      <div class="justify-between flex flex-row  items-start pl-4 p-3 mx-3 bg-[#fff] mt-2">
          <img src="<%= (url_for(group.icon))%>" class="h-[2.5rem]"/>
        
          <div class="flex flex-col space-y-2 ">
            <p><%= group.name %></p>
            <p><%= group.created_at.asctime%></p>  
          </div>
          <p class="flex flex-row justify-end w-[70px] font-bold text-black">$<%= group.entities.sum(:amount)%></p> 
      </div>

     <%end%>
  <%end%>
 <%end%>

  <% if @groups.empty? %>
    <p class='text-center text-text-primary text-md'>No categories yet</p>
  <% end %>
  

  

</div>
<%= link_to 'New Category', new_group_path,class: "z-30 fixed sm:hidden bottom-0 md:bottom-6 w-full text-center bg-secondary hover:bg-primary hover:opacity-50 text-[#fff] font-bold py-3 px-4 border border-primary rounded" %>

app/views/groups/new.html.erb
  
<div>
  <h1 class=" text-center p-3 text-xl font-bold text-text-primary">Add New Category</h1>

  <%= render 'form'%>
<div>

app/views/groups/show.html.erb
<div class="flex flex-col space-y-3">

<% if can? :manage, @group%>
  <div class="flex flex-row justify-between items-center px-4 py-2 mb-2 text-text-primary bg-[#fff]">
      <img src="<%= (url_for(@group.icon))%>" class="h-[2.5rem]"/>
      <p class="text-text-primary text-lg"><%= @group.name %></p>
      <p class="text-black font-bold">$<%= @group.entities.sum(:amount)%></p>
  </div>

  <%= link_to 'New Transaction', new_group_entity_path(@group),class: " hidden sm:block self-center md:bottom-6 w-25 text-center bg-secondary hover:bg-primary hover:opacity-50 text-[#fff] font-bold py-3 px-4 border border-primary rounded" %>


  <div class="flex flex-col space-y-2">
    <% @group.entities.each do |entity| %>
    <div class='bg-[#fff] px-4 py-3 m-3 text-text-primary'>
      <div class="flex flex-row justify-between items-center">
        <p><%= entity.name %></p>
        <p class="font-bold text-black">$<%= entity.amount %></p>
      </div>
      <p><%= entity.created_at.asctime %></p>
    </div>
    <% end %>
  </div>
<%end%>
  <% if @group.entities.empty? %>
    <p class='text-center text-text-primary text-md'>No entities yet</p>
  <% end %>

  

</div>

<%= link_to 'New Transaction', new_group_entity_path(@group),class: "z-30 fixed sm:hidden bottom-0 md:bottom-6 w-full text-center bg-secondary hover:bg-primary hover:opacity-50 text-[#fff] font-bold py-3 px-4 border border-primary rounded" %>

app/views/layouts/_navbar.html.erb
<%if user_signed_in?%>
<nav class= "sm:block fixed top-0 w-full z-50" data-hamburger-target="nav">
  <div  class=" bg-primary flex flex-wrap justify-between items-center mx-auto p-2 md:px-6 " >
   
    <%= link_to 'Budget App',groups_path,class:"self-center text-xl font-semibold whitespace-nowrap dark:text-[#fff] hidden md:block text-[#fff]"%>
    <button data-action="click->hamburger#toggleMenu" data-hamburger-target="menuIcon" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-[#fff] rounded-lg md:hidden  hover:bg-primary hover:opacity-50 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600">
      <span class="sr-only">Open main menu</span>
      <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
    </button>
    <div data-hamburger-target="menu" class="hidden md:block flex flex-col gap-y-3 z-40 md:w-auto h-[100vh] md:h-auto w-[50vw] bg-primary text-[#fff] overflow-y-hidden" id="navbar-default">
          <button class=" md:hidden text-[#fff] place-self-end m-3" data-action="click->hamburger#closeMenu">
            <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><!--! Font Awesome Pro 6.1.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M310.6 361.4c12.5 12.5 12.5 32.75 0 45.25C304.4 412.9 296.2 416 288 416s-16.38-3.125-22.62-9.375L160 301.3L54.63 406.6C48.38 412.9 40.19 416 32 416S15.63 412.9 9.375 406.6c-12.5-12.5-12.5-32.75 0-45.25l105.4-105.4L9.375 150.6c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0L160 210.8l105.4-105.4c12.5-12.5 32.75-12.5 45.25 0s12.5 32.75 0 45.25l-105.4 105.4L310.6 361.4z"/></svg>
          </button>
      
      <ul class=" flex flex-col pl-[12vw] mt-4 rounded-lg md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0">
          
       <% if user_signed_in?%>
          <li>
            <%= link_to  "Home", groups_path ,class:'block py-2 pr-4 pl-3 text-[#fff] bg-primary rounded md:bg-transparent  md:p-0 dark:text-[#fff]'%>
          </li>
          <li>
            <%= link_to  "Categories", groups_path ,class:'block py-2 pr-4 pl-3 text-[#fff] bg-primary rounded md:bg-transparent  md:p-0 dark:text-[#fff]'%>
          </li>
          <li>
            <%= link_to  "Log out", destroy_user_session_path ,data: { turbo_method: :delete } ,class:'block py-2 pr-4 pl-3 text-[#fff] bg-primary rounded md:bg-transparent  md:p-0 dark:text-[#fff]'%>
          </li>
       <%else%>
          <li>
            <%= link_to  "Log in", user_session_path ,class:'block py-2 pr-4 pl-3 text-[#fff] bg-primary rounded md:bg-transparent md:p-0 dark:text-[#fff]'%>
          </li>
          <li>
            <%= link_to  "Sign up", new_user_registration_path ,class:'block py-2 pr-4 pl-3 text-[#fff] bg-primary rounded md:bg-transparent md:p-0 dark:text-[#fff]'%> 
          </li>
        <%end%>
    
      </ul>
    </div>

    <div data-hamburger-target='navbarHeading' class="sm:hidden">
    <% if controller_name == 'groups' && action_name=='show'%>
      <h2 class="text-[#fff] uppercase text-lg">Transactions</h2>
    <%elsif controller_name == 'groups' && action_name =='index'%>
      <h2 class="text-[#fff] uppercase text-lg">Categories</h2>
    <%elsif controller_name == 'entities' && action_name =='show'%>
      <h2 class="text-[#fff] uppercase text-lg">Transaction details</h2>
    <%end%>
    </div>
    <button data-hamburger-target='searchIcon' type="button" class="inline-flex items-center p-2 ml-3 text-sm text-[#fff] rounded-lg md:hidden hover:bg-primary hover:opacity-50 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600">
    <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M500.3 443.7l-119.7-119.7c27.22-40.41 40.65-90.9 33.46-144.7C401.8 87.79 326.8 13.32 235.2 1.723C99.01-15.51-15.51 99.01 1.724 235.2c11.6 91.64 86.08 166.7 177.6 178.9c53.8 7.189 104.3-6.236 144.7-33.46l119.7 119.7c15.62 15.62 40.95 15.62 56.57 0C515.9 484.7 515.9 459.3 500.3 443.7zM79.1 208c0-70.58 57.42-128 128-128s128 57.42 128 128c0 70.58-57.42 128-128 128S79.1 278.6 79.1 208z"/></svg>
    </button>
  </div>
</nav>
<%else%>

<nav class= "hidden sm:block fixed top-0 w-full z-50">
  <div  class=" bg-primary flex flex-wrap justify-between items-center mx-auto p-2 md:px-6 " >
   
    <%= link_to 'Budget App',groups_path,class:"self-center text-xl font-semibold whitespace-nowrap dark:text-[#fff] hidden md:block text-[#fff]"%>

      
      <ul class=" flex flex-col pl-[12vw] mt-4 rounded-lg md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0">
          
          <li>
            <%= link_to  "Log in", user_session_path ,class:'block py-2 pr-4 pl-3 text-[#fff] bg-primary rounded md:bg-transparent md:p-0 dark:text-[#fff]'%>
          </li>
          <li>
            <%= link_to  "Sign up", new_user_registration_path ,class:'block py-2 pr-4 pl-3 text-[#fff] bg-primary rounded md:bg-transparent md:p-0 dark:text-[#fff]'%> 
          </li>
      
    
      </ul>
  </div>
</nav>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html >
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload"%>
    <%= javascript_importmap_tags%>
    
  </head>

  <body data-controller="hamburger" class="min-h-screen bg-text-primary bg-opacity-[0.2]">
 
  <%= render 'layouts/navbar' %>
    
    <div class="sm:h-auto overflow-hidden sm:overflow-auto" data-action="click->hamburger#closeMenu">
      <% if user_signed_in?%>
        <div class="mt-14 text-center">
          <%= render 'shared/flashes' %>
        </div>
      <%else%>
        <div class="mt-14 text-center">
          <%= render 'shared/flashes' %>
        </div>
      <%end%>
       
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% flash.each do |type, msg| %>
  <div class='mt-[2rem]'>
    <%= msg %>
  </div>
<% end %>